apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-auth-to-mysql
  labels:
    app: summarize-ai-auth
spec:
  podSelector:
    matchLabels:
      app: summarize-ai-auth-mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: summarize-ai-auth
      ports:
        - protocol: TCP
          port: 3306