apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-auth-to-mysql
  labels:
    app: {{ include "summarize-ai-auth.name" . }}
spec:
  podSelector:
    matchLabels:
      app: mysql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "summarize-ai-auth.name" . }}
      ports:
        - protocol: TCP
          port: 3306