apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  APP_SECRET_KEY: {{ .Values.secrets.appSecretKey | b64enc }}
  SQL_USER: {{ .Values.secrets.sqlUser | b64enc }}
  SQL_PASSWORD: {{ .Values.secrets.sqlPassword | b64enc }}
  SQL_DB: {{ .Values.secrets.sqlDb | b64enc }}