# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "summarize-ai-auth.fullname" . }}
#   labels:
#     app: {{ include "summarize-ai-auth.name" . }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: 5000
#   selector:
#     app: {{ include "summarize-ai-auth.name" . }}